; Generated by c86 (BYU-NASM) 5.1 (beta) from lab4_app.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
L_lab4_app_5:
	DB	"Max: ",0
L_lab4_app_4:
	DB	"Min: ",0
L_lab4_app_3:
	DB	0x9,0
L_lab4_app_2:
	DB	"Ticks: ",0
L_lab4_app_1:
	DB	"! Dropped msgs: tick ",0
	ALIGN	2
ATask:
	; >>>>> Line:	26
	; >>>>> { 
	jmp	L_lab4_app_6
L_lab4_app_7:
	; >>>>> Line:	30
	; >>>>> min = 100; 
	mov	word [bp-4], 100
	; >>>>> Line:	31
	; >>>>> max = 0; 
	mov	word [bp-6], 0
	; >>>>> Line:	32
	; >>>>> count = 0; 
	mov	word [bp-8], 0
	; >>>>> Line:	34
	; >>>>> while (1) 
	jmp	L_lab4_app_9
L_lab4_app_8:
	; >>>>> Line:	36
	; >>>>> tmp = (struct msg *) YKQPend(MsgQPtr); 
	push	word [MsgQPtr]
	call	YKQPend
	add	sp, 2
	mov	word [bp-2], ax
	; >>>>> Line:	39
	; >>>>> if (tmp->tick != count+1) 
	mov	ax, word [bp-8]
	inc	ax
	mov	si, word [bp-2]
	mov	dx, word [si]
	cmp	dx, ax
	je	L_lab4_app_11
	; >>>>> Line:	41
	; >>>>> print(" 
	mov	ax, 21
	push	ax
	mov	ax, L_lab4_app_1
	push	ax
	call	print
	add	sp, 4
	; >>>>> Line:	42
	; >>>>> if (tmp->tick - (count+1) > 1) { 
	mov	si, word [bp-2]
	mov	ax, word [si]
	sub	ax, word [bp-8]
	dec	ax
	cmp	ax, 1
	jle	L_lab4_app_12
	; >>>>> Line:	43
	; >>>>> printInt(count+1); 
	mov	ax, word [bp-8]
	inc	ax
	push	ax
	call	printInt
	add	sp, 2
	; >>>>> Line:	44
	; >>>>> printChar('-'); 
	mov	al, 45
	push	ax
	call	printChar
	add	sp, 2
	; >>>>> Line:	45
	; >>>>> printInt(tmp->tick-1); 
	mov	si, word [bp-2]
	mov	ax, word [si]
	dec	ax
	push	ax
	call	printInt
	add	sp, 2
	; >>>>> Line:	46
	; >>>>> printNewLine(); 
	call	printNewLine
	jmp	L_lab4_app_13
L_lab4_app_12:
	; >>>>> Line:	49
	; >>>>> printInt(tmp->tick-1); 
	mov	si, word [bp-2]
	mov	ax, word [si]
	dec	ax
	push	ax
	call	printInt
	add	sp, 2
	; >>>>> Line:	50
	; >>>>> printNewLine(); 
	call	printNewLine
L_lab4_app_13:
L_lab4_app_11:
	; >>>>> Line:	55
	; >>>>> count = tmp->tick; 
	mov	si, word [bp-2]
	mov	ax, word [si]
	mov	word [bp-8], ax
	; >>>>> Line:	58
	; >>>>> if (tmp->data < min) 
	mov	si, word [bp-2]
	add	si, 2
	mov	ax, word [bp-4]
	cmp	ax, word [si]
	jle	L_lab4_app_14
	; >>>>> Line:	59
	; >>>>> min = tmp->data; 
	mov	si, word [bp-2]
	add	si, 2
	mov	ax, word [si]
	mov	word [bp-4], ax
L_lab4_app_14:
	; >>>>> Line:	60
	; >>>>> if (tmp->data > max) 
	mov	si, word [bp-2]
	add	si, 2
	mov	ax, word [bp-6]
	cmp	ax, word [si]
	jge	L_lab4_app_15
	; >>>>> Line:	61
	; >>>>> max = tmp->data; 
	mov	si, word [bp-2]
	add	si, 2
	mov	ax, word [si]
	mov	word [bp-6], ax
L_lab4_app_15:
	; >>>>> Line:	64
	; >>>>> print(" 
	mov	ax, 7
	push	ax
	mov	ax, L_lab4_app_2
	push	ax
	call	print
	add	sp, 4
	; >>>>> Line:	65
	; >>>>> printInt(count); 
	push	word [bp-8]
	call	printInt
	add	sp, 2
	; >>>>> Line:	66
	; >>>>> print("\t", 1); 
	mov	ax, 1
	push	ax
	mov	ax, L_lab4_app_3
	push	ax
	call	print
	add	sp, 4
	; >>>>> Line:	67
	; >>>>> print("Min: ", 5); 
	mov	ax, 5
	push	ax
	mov	ax, L_lab4_app_4
	push	ax
	call	print
	add	sp, 4
	; >>>>> Line:	68
	; >>>>> printInt(min); 
	push	word [bp-4]
	call	printInt
	add	sp, 2
	; >>>>> Line:	69
	; >>>>> print("\t", 1); 
	mov	ax, 1
	push	ax
	mov	ax, L_lab4_app_3
	push	ax
	call	print
	add	sp, 4
	; >>>>> Line:	70
	; >>>>> print("Max: ", 5); 
	mov	ax, 5
	push	ax
	mov	ax, L_lab4_app_5
	push	ax
	call	print
	add	sp, 4
	; >>>>> Line:	71
	; >>>>> printInt(max); 
	push	word [bp-6]
	call	printInt
	add	sp, 2
	; >>>>> Line:	72
	; >>>>> printNewLine(); 
	call	printNewLine
L_lab4_app_9:
	jmp	L_lab4_app_8
L_lab4_app_10:
	mov	sp, bp
	pop	bp
	ret
L_lab4_app_6:
	push	bp
	mov	bp, sp
	sub	sp, 8
	jmp	L_lab4_app_7
	ALIGN	2
BTask:
	; >>>>> Line:	77
	; >>>>> { 
	jmp	L_lab4_app_17
L_lab4_app_18:
	; >>>>> Line:	81
	; >>>>> curval = 1001; 
	mov	word [bp-4], 1001
	; >>>>> Line:	82
	; >>>>> chcount = 0; 
	mov	word [bp-10], 0
	; >>>>> Line:	84
	; >>>>> while (1) 
	jmp	L_lab4_app_20
L_lab4_app_19:
	; >>>>> Line:	86
	; >>>>> YKDelayTask(2); 
	mov	ax, 2
	push	ax
	call	YKDelayTask
	add	sp, 2
	; >>>>> Line:	88
	; >>>>> if (GlobalFlag == 1) 
	cmp	word [GlobalFlag], 1
	jne	L_lab4_app_22
	; >>>>> Line:	90
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	91
	; >>>>> busycount = YKTickNum; 
	mov	ax, word [YKTickNum]
	mov	word [bp-2], ax
	; >>>>> Line:	92
	; >>>>> } 
	call	YKExitMutex
	; >>>>> Line:	94
	; >>>>> while (1) 
	jmp	L_lab4_app_24
L_lab4_app_23:
	; >>>>> Line:	96
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	97
	; >>>>> tickNum = YKTickNum; 
	mov	ax, word [YKTickNum]
	mov	word [bp-12], ax
	; >>>>> Line:	98
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	99
	; >>>>> if(tickNum >= busycount + 5) break; 
	mov	ax, word [bp-2]
	add	ax, 5
	mov	dx, word [bp-12]
	cmp	dx, ax
	jb	L_lab4_app_26
	; >>>>> Line:	99
	; >>>>> if(tickNum >= busycount + 5) break; 
	jmp	L_lab4_app_25
L_lab4_app_26:
	; >>>>> Line:	101
	; >>>>> curval += 2; 
	add	word [bp-4], 2
	; >>>>> Line:	102
	; >>>>> flag = 0; 
	mov	word [bp-8], 0
	; >>>>> Line:	103
	; >>>>> for (j = 3; (j*j) < curval; j += 2) 
	mov	word [bp-6], 3
	jmp	L_lab4_app_28
L_lab4_app_27:
	; >>>>> Line:	105
	; >>>>> if (curval % j == 0) 
	mov	ax, word [bp-4]
	cwd
	idiv	word [bp-6]
	mov	ax, dx
	test	ax, ax
	jne	L_lab4_app_31
	; >>>>> Line:	107
	; >>>>> flag = 1; 
	mov	word [bp-8], 1
	; >>>>> Line:	108
	; >>>>> break; 
	jmp	L_lab4_app_29
L_lab4_app_31:
L_lab4_app_30:
	add	word [bp-6], 2
L_lab4_app_28:
	mov	ax, word [bp-6]
	imul	word [bp-6]
	mov	dx, word [bp-4]
	cmp	dx, ax
	jg	L_lab4_app_27
L_lab4_app_29:
	; >>>>> Line:	111
	; >>>>> if (!fl 
	mov	ax, word [bp-8]
	test	ax, ax
	jne	L_lab4_app_32
	; >>>>> Line:	113
	; >>>>> printChar('.'); 
	mov	al, 46
	push	ax
	call	printChar
	add	sp, 2
	; >>>>> Line:	114
	; >>>>> if (++chcount > 75) 
	mov	ax, word [bp-10]
	inc	ax
	mov	word [bp-10], ax
	cmp	ax, 75
	jle	L_lab4_app_33
	; >>>>> Line:	116
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	117
	; >>>>> chcount = 0; 
	mov	word [bp-10], 0
L_lab4_app_33:
L_lab4_app_32:
L_lab4_app_24:
	jmp	L_lab4_app_23
L_lab4_app_25:
	; >>>>> Line:	121
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	122
	; >>>>> chcount = 0; 
	mov	word [bp-10], 0
	; >>>>> Line:	123
	; >>>>> GlobalFlag = 0; 
	mov	word [GlobalFlag], 0
L_lab4_app_22:
L_lab4_app_20:
	jmp	L_lab4_app_19
L_lab4_app_21:
	mov	sp, bp
	pop	bp
	ret
L_lab4_app_17:
	push	bp
	mov	bp, sp
	sub	sp, 12
	jmp	L_lab4_app_18
L_lab4_app_39:
	DB	"% >>>>>",0xD,0xA,0
L_lab4_app_38:
	DB	", CPU usage: ",0
L_lab4_app_37:
	DB	"<<<<< Context switches: ",0
L_lab4_app_36:
	DB	"Determining CPU capacity",0xD,0xA,0
L_lab4_app_35:
	DB	"Welcome to the YAK kernel",0xD,0xA,0
	ALIGN	2
STask:
	; >>>>> Line:	129
	; >>>>> { 
	jmp	L_lab4_app_40
L_lab4_app_41:
	; >>>>> Line:	133
	; >>>>> YKDelayTask(1); 
	mov	ax, 1
	push	ax
	call	YKDelayTask
	add	sp, 2
	; >>>>> Line:	134
	; >>>>> printString("Welcome to the YAK kernel\r\n"); 
	mov	ax, L_lab4_app_35
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	135
	; >>>>> printString( 
	mov	ax, L_lab4_app_36
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	136
	; >>>>> YKDelayTask(1); 
	mov	ax, 1
	push	ax
	call	YKDelayTask
	add	sp, 2
	; >>>>> Line:	137
	; >>>>> YKIdleCount = 0; 
	mov	word [YKIdleCount], 0
	; >>>>> Line:	138
	; >>>>> YKDelayTask(5); 
	mov	ax, 5
	push	ax
	call	YKDelayTask
	add	sp, 2
	; >>>>> Line:	139
	; >>>>> max = YKIdleCount / 25; 
	mov	ax, word [YKIdleCount]
	xor	dx, dx
	mov	cx, 25
	div	cx
	mov	word [bp-2], ax
	; >>>>> Line:	140
	; >>>>> YKIdleCount = 0; 
	mov	word [YKIdleCount], 0
	; >>>>> Line:	142
	; >>>>> YKNewTask(BTask, (void *) &BTaskStk[512], 10); 
	mov	ax, 10
	push	ax
	mov	ax, (BTaskStk+1024)
	push	ax
	mov	ax, BTask
	push	ax
	call	YKNewTask
	add	sp, 6
	; >>>>> Line:	143
	; >>>>> YKNewTask(ATask, (void *) &ATaskStk[512], 20); 
	mov	ax, 20
	push	ax
	mov	ax, (ATaskStk+1024)
	push	ax
	mov	ax, ATask
	push	ax
	call	YKNewTask
	add	sp, 6
	; >>>>> Line:	145
	; >>>>> while (1) 
	jmp	L_lab4_app_43
L_lab4_app_42:
	; >>>>> Line:	147
	; >>>>> YKDelayTask(20); 
	mov	ax, 20
	push	ax
	call	YKDelayTask
	add	sp, 2
	; >>>>> Line:	149
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	150
	; >>>>> switchCount = YKCtxSwCount; 
	mov	ax, word [YKCtxSwCount]
	mov	word [bp-4], ax
	; >>>>> Line:	151
	; >>>>> idleCount = YKIdleCount; 
	mov	ax, word [YKIdleCount]
	mov	word [bp-6], ax
	; >>>>> Line:	152
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	154
	; >>>>> printString("<<<<< Context switches: "); 
	mov	ax, L_lab4_app_37
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	155
	; >>>>> printInt((int)switchCount); 
	push	word [bp-4]
	call	printInt
	add	sp, 2
	; >>>>> Line:	156
	; >>>>> printStri 
	mov	ax, L_lab4_app_38
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	157
	; >>>>> tmp = (int) (idleCount/max); 
	mov	ax, word [bp-6]
	xor	dx, dx
	div	word [bp-2]
	mov	word [bp-8], ax
	; >>>>> Line:	158
	; >>>>> printInt(100-tmp); 
	mov	ax, 100
	sub	ax, word [bp-8]
	push	ax
	call	printInt
	add	sp, 2
	; >>>>> Line:	159
	; >>>>> printString("% >>>>>\r\n"); 
	mov	ax, L_lab4_app_39
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	161
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	162
	; >>>>> YKCtxSwCount = 0; 
	mov	word [YKCtxSwCount], 0
	; >>>>> Line:	163
	; >>>>> YKIdleCount = 0; 
	mov	word [YKIdleCount], 0
	; >>>>> Line:	164
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
L_lab4_app_43:
	jmp	L_lab4_app_42
L_lab4_app_44:
	mov	sp, bp
	pop	bp
	ret
L_lab4_app_40:
	push	bp
	mov	bp, sp
	sub	sp, 8
	jmp	L_lab4_app_41
	ALIGN	2
main:
	; >>>>> Line:	169
	; >>>>> { 
	jmp	L_lab4_app_46
L_lab4_app_47:
	; >>>>> Line:	170
	; >>>>> YKInitialize(); 
	call	YKInitialize
	; >>>>> Line:	173
	; >>>>> GlobalFlag = 0; 
	mov	word [GlobalFlag], 0
	; >>>>> Line:	174
	; >>>>> MsgQPtr = YKQCreate(MsgQ, 10); 
	mov	ax, 10
	push	ax
	mov	ax, MsgQ
	push	ax
	call	YKQCreate
	add	sp, 4
	mov	word [MsgQPtr], ax
	; >>>>> Line:	175
	; >>>>> YKNewTask(STask, (void *) &STaskStk[512], 30); 
	mov	ax, 30
	push	ax
	mov	ax, (STaskStk+1024)
	push	ax
	mov	ax, STask
	push	ax
	call	YKNewTask
	add	sp, 6
	; >>>>> Line:	177
	; >>>>> YKRun(); 
	call	YKRun
	mov	sp, bp
	pop	bp
	ret
L_lab4_app_46:
	push	bp
	mov	bp, sp
	jmp	L_lab4_app_47
	ALIGN	2
MsgArray:
	TIMES	80 db 0
ATaskStk:
	TIMES	1024 db 0
BTaskStk:
	TIMES	1024 db 0
STaskStk:
	TIMES	1024 db 0
GlobalFlag:
	TIMES	2 db 0
MsgQ:
	TIMES	20 db 0
MsgQPtr:
	TIMES	2 db 0
